export const genreOptions: string[] = [
  'Fantasy',
  'Science Fiction',
  'Horror',
  'Romance',
  'Thriller',
  'Mystery',
  'Detective',
  'Dystopian',
  'Memoir',
  'Historical Fiction',
  'Cook Book',
  'Autobiography',
  'Biography',
  'Self Help',
];
